---
- name: Provision coding-vm
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - global_vars.yml
  tasks:
  # Files and folders
    - name: create folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ SSH_USER }}"
        group: "{{ SSH_USER }}"
        mode: '0700'
      loop:
        - /home/{{ SSH_USER }}/.ssh/config.d
        - /home/{{ SSH_USER }}/config

    - name : Create empty .gitconfig
      ansible.builtin.file:
        path: /home/{{ SSH_USER }}/.gitconfig
        state: touch
        owner: "{{ SSH_USER }}"
        group: "{{ SSH_USER }}"
        mode: '0644'

# First set of paquet

    - name: Remove apt lock
      ansible.builtin.file:
        path: /var/lib/dpkg/lock-frontend
        state: absent

    - name: Install packages (1/2)
      ansible.builtin.apt:
        name:
          - curl
          - docker
          - fish
          - git
          - gnupg
          - gpg
          - jq
          - locate
          - openssh-client
          - original-awk
          - podman
          - software-properties-common
          - terminator
          - tree
          - vim
          - wget
          - whois
          - yq
        state: present
        update_cache: yes

    - name: Install Az-Cli
      ansible.builtin.shell: |
        curl -fsSL 'https://azurecliprod.blob.core.windows.net/$root/deb_install.sh' | sudo bash
# SSH
    - name: Copy SSH_USER private key
      ansible.builtin.copy:
        src: "{{ SSH_USER_PRIVATE_KEY_PATH }}"
        dest: /home/{{ SSH_USER }}/.ssh/
        owner: "{{ SSH_USER }}"
        group: "{{ SSH_USER }}"
        mode: '0600'
    
    - name: Include config.d in ssh config
      ansible.builtin.lineinfile: 
        path: /home/{{ SSH_USER }}/.ssh/config
        line: "Include config.d/*"
        create: yes
        owner: "{{ SSH_USER }}"
        group: "{{ SSH_USER }}"
        mode: '0644'

    - name: Set up github SSH connections
      ansible.builtin.copy:
        content: |
          host git-perso
            hostname github.com
            User youpi-tralala
            IdentityFile ~/.ssh/yves@proton

          host github.com
          	hostname github.com
            User youpi-tralala
            IdentityFile ~/.ssh/yves@onepoint      
        dest: /home/{{ SSH_USER }}/.ssh/config.d/github
        owner: "{{ SSH_USER }}"
        group: "{{ SSH_USER }}"
        mode: '0644'
    
#    - name: Configure line ending as LF for git
#      ansible.builtin.git_config:
#        name: core.autocrlf
#        scope: global
#        value: false

    - name: Configure line ending as LF for git
      ansible.builtin.shell: git config --global core.autocrlf false

    
# Zscaler
    - name: Bypass ZSScaler certificate
      ansible.builtin.copy:
        src: zscaler.crt
        dest: /usr/local/share/ca-certificates/zscaler.crt
        owner: root
        group: root
        mode: '0644'
    - name: Update CA certificates
      ansible.builtin.command: update-ca-certificates
      
# Add Terraform repo
    - name: Add the HashiCorp GPG key
      ansible.builtin.shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg | \
        gpg --dearmor | \
        sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
    
    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
        filename: hashicorp

# Add Powershell repo
    - name: Add Microsoft GPG key
      ansible.builtin.shell: |
        wget -q https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb

# Second  set of paquets
    - name: Install packages (2/2)
      ansible.builtin.apt:
        name:
          - powershell
          - terraform
        state: present
        update_cache: yes
